### PR TITLE
fixed email form validation issue

### PR DESCRIPTION
**Pull request by dmc2015**
screen shot 2015-08-12 at 2 46 39 pm

### CODE REVIEW

**Comment by dmc2015** [comment]
There is an issue on lesson02-03, in the index.html a 'required' is needed as an attribute for the email 'input' or the email regex is not considered required for form validation.

**Comment by victorkane** [comment]
Actually, the absence of a required attribute is by design to demonstrate in opposition to the other two fields. Email simply validates that it is a correct email format. So, "by design". Thanks a million for an excellent suggestion, however.

**Comment by dmc2015** [comment]
Shouldn't the 'Sign In' button be grey until there is a valid e-mail in the e-mail input box?

**Comment by victorkane** [comment]
It's a valid alternative, but not necessarily so. It's purely a functional
question. I wanted people not to have to leave their mail if they didn't
want to. The UUID that users have don't require email for unique id.

**Comment by victorkane** [comment]
With the example given, it's easy to add it if you want to use the code for
your own app.

**Comment by dmc2015** [comment]
I see now, thank you.

**Comment by victorkane** [comment]
Of course, the point you're making is an excellent usability one.

**Pull request closed without merging**
